import {
	CV_API_HOST,
	CV_STATIC_IMAGES_HOST,
	CV_IMAGES_API_PATH,
} from "../../environment";

export default [
	{
		id: "user",
		label: "User Id",
		placeholder: "Owner user id",
		input: "text",
		value: '',
		required: true,
	},
	{
		id: "fullName",
		label: "Full Name",
		placeholder: "Full name",
		input: "text",
		value: '',
		required: true,
	},
	{
		id: "headline",
		label: "Headline",
		placeholder: "Professional headline",
		input: "text",
		value: '',
		required: true,
	},
	{
		id: "city",
		label: "City",
		placeholder: "City",
		input: "text",
		value: '',
		required: true,
	},
	{
		id: "photo",
		label: "Photo",
		input: "file",
		value: '',
		file: true,
		accept: "image/*",
		apiHost: CV_API_HOST,
		imageHost: CV_STATIC_IMAGES_HOST,
		apiPath: CV_IMAGES_API_PATH,
	},
	{
		id: "profileSummary",
		label: "Profile Summary",
		placeholder: "Profile summary",
		input: "text",
		value: '',
		required: true,
	},
	{
		id: "skills",
		label: "Skills",
		input: "sublist",
		value: [],
	},
	{
		id: "contactLinks",
		label: "Contact Links",
		input: "sublist",
		value: [],
		structure: [
			{
				id: "label",
				label: "Label",
				placeholder: "e.g. LinkedIn, GitHub",
				input: "text",
				value: '',
				required: true,
			},
			{
				id: "url",
				label: "URL",
				placeholder: "Link URL",
				input: "text",
				value: '',
				required: true,
			},
		],
	},
	{
		id: "createdAt",
		label: "Created At",
		placeholder: "Created at",
		input: "datetime",
		value: '',
	},
	{
		id: "updatedAt",
		label: "Updated At",
		placeholder: "Updated at",
		input: "datetime",
		value: '',
	},
];
